title = "Archivo histórico digital de la revista Pelo"
languageCode = "es-ar"

baseurl = "http://www.revistapelo.com.ar/"
googleAnalytics = "UA-108028361-1"

bind = "0.0.0.0"
port = 3000

[taxonomies]
artista = "artistas"
colaborador = "colaboradores"
disco-libro = "discos-libros"
pelicula = "peliculas"
espacio = "espacios"
evento = "eventos"
disco = "discos"
libro = "libros"
medio = "medios"

[params]
dateFormat = "2006"
filesUrl = "http://files.revistapelo.com.ar/"
siteDescription = "Sitio de la digitalización de la revista Pelo, editada en Buenos Aires"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
