title = "Digitalización de la revista Pelo"
languageCode = "es-ar"

baseurl = "http://www.revistapelo.com.ar/"

bind = "0.0.0.0"
port = 3000

[taxonomies]
artista = "artistas"
colaborador = "colaboradores"
espacio = "espacios"
evento = "eventos"
disco-libro = "discos-libros"
pelicula = "peliculas"
medio = "medios"

[params]
dateFormat = "2006"
filesUrl = "http://files.revistapelo.com.ar/"
siteDescription = "Sitio de la digitalización de la revista Pelo, editada en Buenos Aires"
