baseurl = "http://revistapelo.herokuapp.com/"
title = "Digitalización de la revista Pelo"
languageCode = "es-ar"

theme = "hugo_theme_robust"
bind = "0.0.0.0"
port = 3000

[taxonomies]
genero = "generos"
artista = "artistas"
