FROM ruby:3.4.9

ARG USER_NAME
ARG USER_UID
ARG USER_GID

RUN addgroup --gid $USER_GID $USER_NAME && adduser --disabled-password --gecos '' --uid $USER_UID --gid $USER_GID $USER_NAME

RUN export DEBIAN_FRONTEND=noninteractive && apt-get -y update && \
    apt-get -y --no-install-recommends install ca-certificates curl git gh unzip make gcc libc6-dev && \
    apt-get -y autoremove && apt-get clean && rm -rf /var/lib/apt/lists/*

# Install Hugo extended via prebuilt binary
RUN HUGO_VERSION=0.145.0 && \
    curl -fsSL "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.tar.gz" | tar -xz -C /usr/local/bin hugo && \
    gem install html-proofer

USER $USER_NAME
